### ISSUE TITLE
arachni or sqlmap wont work 

### ISSUE THREAD

**Issue by Digiguy1** [fcavallarin/htcap#37]
in the /core/scan/scanner/arachni.py  same for sqlmap.py

i change the scanner exe /usr/share/arachni/bin/arachni
to /home/arachni/bin/arachni because that's where i have the arachni framework but doesn't work
it always worked for me in the previous versions https://github.com/Vulnerability-scanner/htcap  
but in this version i only get this arachni executable not found can you please help ?

**Comment by segment-srl** [comment]
things are changed in the new version ... now you can specify the arachni bin dir with the -x option (option of the scanner module) . In your case you may run:

htcap scan arachni test.db -x /home/arachni/bin


-f

**Comment by Digiguy1** [comment]
is it possibly to change the default directory from the script ???

**Comment by segment-srl** [comment]
you can modify the following two lines and put the full path

self.acmd = "arachni"
self.rcmd = "arachni_reporter" 


alternatively you can add '/home/arachni/bin/' to your $PATH environment variable

**Comment by Digiguy1** [comment]
hi your answers solve my problems in the older versions but the new one im having a problem with sqlmap i set the path to the directory where i have sqlmap but is not working can you please help me here is what im doing 

def get_settings(self):
		return dict(
			request_types = "xhr,link,form,jsonp,redirect,fetch",
			num_threads = 5,
			process_timeout = 300,
			scanner_exe = "/hacktools/webtools/htcap/sqlmap/sqlmap.py"

but not working
