### ISSUE TITLE
problematic parameter(-x)

### ISSUE THREAD

**Issue by maybe-why-not** [fcavallarin/htcap#67]
command:python htcap.py crawl -p http:127.0.0.1:8080 -m aggressive -c "security_level=0; PHPSESSID=1ln04buglpc7ljdt95nu0r4a75" -x '.*logout.*' http://192.168.88.136/bWAPP/bWAPP/sqli_6.php baidu3.db
-x can't exclude (regex) logout urls,
and script can't auto click button to post requests.
![image](https://user-images.githubusercontent.com/29968903/65399622-56d1f280-ddf0-11e9-8486-a7647c560fb1.png)

Short Video in https://htcap.org is so cool! But i don't know how to repeat.

**Comment by fcavallarin** [comment]
I'm unable to reproduce the issues. Is there any special setting or it's a standard bWAPP install?

**Comment by maybe-why-not** [comment]
> I'm unable to reproduce the issues. Is there any special setting or it's a standard bWAPP install?

You can try this online shooting range.(http://bwapp.ywnxs.com/sqli_6.php)
username/password: bee/bug
![image](https://user-images.githubusercontent.com/29968903/66148583-d6a75a80-e643-11e9-9588-dd8e44bd8947.png)

**Comment by fcavallarin** [comment]
Ok, the form issue is due to bug in puppeteer (at least I guess) so I wrote a workaround and now it's working. I'm still unable to reproduce the issue with excluded domains. In your last screenshot you typed '*logout*' instead of '.*logout.*'

**Comment by maybe-why-not** [comment]
![image](https://user-images.githubusercontent.com/29968903/66193672-ac967c80-e6c5-11e9-9c7c-c2ce278734ff.png)

**Comment by fcavallarin** [comment]
I think you should use double quotes and not single quotes... you are on windows ... 
so, try with `".*logout.*"`

**Comment by maybe-why-not** [comment]
Yes, you are right！ This conversation helped me answer the unknown question in advance and avoid my troubles in the future. Bwapp has 158 levels, but only 73 requests have been collected. I think this can give you some inspiration for the linkage between select and button. Thank you for your answer.

**Comment by fcavallarin** [comment]
sounds good! thank you!
