### ISSUE TITLE
Make possible to action on HTML elements without ID

### ISSUE THREAD

**Issue by blackthorne** [fcavallarin/htcap#75]
I was trying to put together a sequence that involves a clickToNativate action but the button I am trying to push does not have an ID that I could pick. I do not know if there is any way around it given its specification. If there is, I would be thankful if you kindly share what that is, otherwise would you consider adding e.g. XPATH support to define elements? 

Thank you

**Comment by fcavallarin** [comment]
XPath support added! now if the selector starts with the '$' char, it will be treated as xpath
