### ISSUE TITLE
sqlmap not working 

### ISSUE THREAD

**Issue by Digiguy1** [fcavallarin/htcap#76]
hi your answers solve my problems in the older versions but the new one im having a problem with sqlmap i set the path to the directory where i have sqlmap but is not working can you please help me here is what im doing

def get_settings(self):
return dict(
request_types = "xhr,link,form,jsonp,redirect,fetch",
num_threads = 5,
process_timeout = 300,
scanner_exe = "/hacktools/webtools/htcap/sqlmap/sqlmap.py"

but not working this is all i get 

Sqlmap executable not found in $PATH

**Comment by fcavallarin** [comment]
fixed, you can use -x also with sqlmap
